import{a as n,i as d,S as u}from"./assets/vendor-e7472c16.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&l(i)}).observe(document,{childList:!0,subtree:!0});function a(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(t){if(t.ep)return;t.ep=!0;const o=a(t);fetch(t.href,o)}})();n.defaults.baseURL="https://api.thecatapi.com/v1/";n.defaults.headers.common["x-api-key"]="live_Q0VNADEy32RTi0X0eKuhYCfTRuaBwaRjJYXAI9dpQx4K9UpiqQs3veVx8O0mXCjR";async function p(){const{data:r}=await n.get("breeds");return r}async function y(r){const{data:e}=await n.get("images/search",{params:{breed_ids:r}});return e}const c=document.querySelector(".breed-select"),f=document.querySelector(".cat-info"),s=document.querySelector(".loader");m();async function m(){c.style.display="none",s.style.display="block";try{const r=await p();c.style.display="flex",h(r)}catch{d.error({timeout:5e3,position:"topRight",message:"Oops! Something went wrong! Try reloading the page!"})}finally{s.style.display="none"}}function h(r){new u({select:c,settings:{showSearch:!1},data:r.map(({name:e,id:a})=>({text:e,value:e,id:a})),events:{beforeChange:()=>f.replaceChildren(),afterChange:g}})}async function g(r){s.style.display="block";try{const e=await y(r[0].id);if(!e.length)throw new Error("Please, select another breed!");f.insertAdjacentHTML("beforeend",w(e[0]))}catch(e){d.error({timeout:1e4,position:"topRight",message:e.message})}finally{s.style.display="none"}}function w({url:r,breeds:e}){return`
    <img class="cat-info__image" src="${r}" >
    <div class="cat-info__info">
      <h2>${e[0].name}</h2>
      <p>${e[0].description}</p>
      <p><strong>Temperament</strong>: ${e[0].temperament}</p>
    </div>
  `}
//# sourceMappingURL=commonHelpers.js.map
